-
  name: install nginx & enable
  hosts: servers
  become: yes
  tasks:
    - name: install nginx
      apt:
        name: nginx
        state: latest
    - name: start & enable
      service:
        name: nginx
        state: started
        enabled: yes
