- 
  name: Patching security
  hosts: servers
  become: yes
  tasks:
   - name: install updates
     apt:
      update_cache: yes
      upgrade: dist

   - name: rebooting system after successfully update
     reboot:
      msg: reboot system after applying updates
      reboot_timeout: 600
      connect_timeout: 5
      pre_reboot_delay: 0
      post_reboot_delay: 30
     when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
